#!/bin/bash
# Bake dashboard/* + assets/logo.svg into cp/embedded_assets.hml as
# Hemlock string constants. Run after editing any of the source files
# to regenerate; output is committed to git so the build itself
# doesn't need to know how to run this.
#
# Why bake in: the witchgrid-cp binary is a single ELF. Reading these
# files from disk at startup would mean operators have to scp a
# `dashboard/` and `assets/` folder alongside the binary or set a
# WITCHGRID_ASSETS env var. Inlining trades ~50 KB of binary size for
# a clean single-file deploy. Same model as Go's embed.FS.
#
# Authoring loop:
#   1. Edit any file under dashboard/ or assets/ as normal.
#   2. Run ./scripts/embed_assets.sh
#   3. Rebuild the CP binary; restart it.

set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PY'
import os

ASSETS = [
    # Pages — one HTML per logical view, served by separate routes
    # so URLs are real + browser back/forward works. Topbar is
    # duplicated across them (cheap; ~20 lines of HTML × 4).
    ("INDEX_HTML",     "dashboard/index.html"),       # /
    ("CATALOG_HTML",   "dashboard/catalog.html"),     # /catalog
    ("TRANSFERS_HTML", "dashboard/transfers.html"),   # /transfers
    ("PROFILES_HTML",  "dashboard/profiles.html"),    # /profiles
    ("BENCH_HTML",     "dashboard/bench.html"),       # /bench
    # Shared assets
    ("STYLES_CSS",     "dashboard/styles.css"),
    ("DASHBOARD_JS",   "dashboard/dashboard.js"),
    ("LOGO_SVG",       "assets/logo.svg"),
]

def hemlock_escape(src: str) -> str:
    return src.replace("\\", "\\\\").replace('"', '\\"')

out = [
    "// AUTO-GENERATED by scripts/embed_assets.sh from:\n",
]
total = 0
for _, path in ASSETS:
    out.append(f"//   {path}\n")
    total += os.path.getsize(path)
out.append("// Edit those source files, then re-run the script — do not edit\n")
out.append("// this file by hand.\n\n")

for name, path in ASSETS:
    src = open(path).read()
    out.append(f'export let {name} = "' + hemlock_escape(src) + '";\n\n')

generated = "".join(out)
open("cp/embedded_assets.hml", "w").write(generated)
print(f"wrote cp/embedded_assets.hml ({len(generated)} bytes from {total} bytes of source)")
PY
